### ISSUE TITLE
Using in vue js

### ISSUE THREAD

**Issue by shrinidhiurala** [filoxo/single-spa-example-rxjs-shared-state#5] opened 2021-08-04 07:04 UTC
```
<template>
    <div class="d-flex align-items-center justify-content-center container">
        <div class="App">
            <div class="w-100 app__container">
                <div class="text-center card" style="width: 50rem;">
                    <nav class="navbar navbar-expand navbar-light bg-light">
                        <a href="#home" class="navbar-brand">Profile</a>
                    </nav>
                    <div class="card-body">
                        <div class="card-title h5">User</div>
                        <p class="card-text"><b>Email:</b> {{email}}</p>

                        <template v-if="email">
                            <button type="button" class="btn btn-primary">Update Info</button>
                        </template>
                        
                    </div>
                    <div class="card-body">
                        <button @click="addButton"  type="button" class="btn btn-primary">Add Nav Count</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    // import HelloWorld from './components/HelloWorld.vue'
    import { auth$ } from "@org/auth";
    export default {
        name: 'App',
        components: {
        },
        data: () => ({
            email: '',
        }),
         
        mounted() {
            this.sub = auth$.subscribe(username => {
                if (username) {
                    // add username/mail to local state if not empty
                    this.email = (username);
                } else {
                    // clear mail
                    this.messages = '';
                }
            });
        },
        beforeUnmount () {
            // unsubscribe to ensure no memory leaks
            //this.sub.unsubscribe();
        },
    }
</script>
```

This is my code, I'm importing auth from Auth application and subscribing it. 

in console it gives follwing error
Uncaught Error: Cannot find module '@org/auth'
on the display it says Module not found in src folder

Any solution to this? Thanks

**Comment by filoxo** [comment] 2021-08-04 17:13
The key is to ensure that the consumer application has this (or all modules named `@org/`) marked as external through the bundler. Then the bundler won't try to find the module in local files.

[vue-cli-plugin-single-spa only adds single-spa to the externals](https://github.com/single-spa/vue-cli-plugin-single-spa/blob/main/index.js#L50) so you need to extend that config to also exclude any additional packages. For another example of that, you can look at [how webpack-config-single-spa sets up externals](https://github.com/single-spa/create-single-spa/blob/main/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L99-L101). What I've done to ease the pain of having to repeat this config is to create a shared webpack config for my own org that our projects will need to consume.

There's also a chance that you might be seeing this due to TypeScript types not being found, which you can find a solution to here: https://stackoverflow.com/a/66401623/2554793

I don't think I can help any further without a reproducible example. But I think your question is answered sufficiently so I'm going to close this issue because its not a bug within my example nor an enhancement that I'll be adding anytime soon. Feel free to continue the discussion though.

**Closed as completed by filoxo** 2021-08-04 17:13 UTC
